name: semgrep-rules-test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test-latest:
    name: rules-test-latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    # TODO: add a pip for opengrep
    - name: install semgrep via pip
      run: pip3 install semgrep
    - name: remove stats directory
      run: rm -rf stats
    - name: validate rules
      run: semgrep validate .
    - name: run semgrep test
      run: semgrep test .
